spring.application.name=tinnova
server.port=8080
server.servlet.context-path=/tinnova

jwt.secret=secretKeyTinnova
jwt.expiration=86400000

### CONFIG BANCO H2 ###
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true
spring.main.allow-bean-definition-overriding=true